newIssueWelcomeComment: >
  Thanks for submitting this issue/request. Your request will be taken for considiration. 
  Please be patient, as the team is not as large and not all requests are good for the bot.